# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_auto_20180716_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
