# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_hours',
            field=models.DateTimeField(null=True),
        ),
    ]
