# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0004_attendance_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total_hours',
            field=models.TimeField(null=True),
        ),
    ]
